# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deco < Formula
  desc "DockerEvironmentCOntrol"
  homepage "https://github.com/YaleUniversity/deco"
  version "1.2.0"
  license "AGPL-3.0-or-later"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YaleUniversity/deco/releases/download/v1.2.0/deco_1.2.0_darwin_amd64.tar.gz"
      sha256 "6d088e6851fee57e130485b42d42491117f0247b0cab5d3518b0241ea0140160"
    end
    if Hardware::CPU.arm?
      url "https://github.com/YaleUniversity/deco/releases/download/v1.2.0/deco_1.2.0_darwin_arm64.tar.gz"
      sha256 "fb6565376f6ac38a745bc10b7fb1c3f9a15c767653186ac449ac16cab4648f89"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/YaleUniversity/deco/releases/download/v1.2.0/deco_1.2.0_linux_amd64.tar.gz"
      sha256 "f4a8cdbe101339ffb27f3da56788b9c980a79f6e2ade4794bfb79162404f7c05"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YaleUniversity/deco/releases/download/v1.2.0/deco_1.2.0_linux_arm64.tar.gz"
      sha256 "76fbc4caf790493eefe86c3ed825444e9932914b4ddeb2b61a134db343c1dcca"
    end
  end

  def install
    bin.install "deco"
  end

  test do
    system "#{bin}/deco", "version"
  end
end
