# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spinup < Formula
  desc "Simple command line interface for spinup"
  homepage "https://github.com/YaleSpinup/spinup-cli"
  version "0.4.0-pre05"
  license "AGPL-3.0-or-later"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/spinup-cli/releases/download/v0.4.0-pre05/spinup-cli_0.4.0-pre05_darwin_amd64.tar.gz"
      sha256 "98295d04fcf47116021c0d99c6f03a7acad58a3d30b67dc90987c1e535740dd4"
    end
    if Hardware::CPU.arm?
      url "https://github.com/YaleSpinup/spinup-cli/releases/download/v0.4.0-pre05/spinup-cli_0.4.0-pre05_darwin_arm64.tar.gz"
      sha256 "c8a0e370e17cb008ea6fd31018a93a5eeb4c61dae80f09d96e1fea438ad47dd0"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/spinup-cli/releases/download/v0.4.0-pre05/spinup-cli_0.4.0-pre05_linux_amd64.tar.gz"
      sha256 "8824b82b664243f34596c9bd74821a24318105d828344f868dd984c88d1ce8ad"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YaleSpinup/spinup-cli/releases/download/v0.4.0-pre05/spinup-cli_0.4.0-pre05_linux_arm64.tar.gz"
      sha256 "e45a27ead65539413b745d6d7da8437656ed60f877dc35f7c2e1ed3b301d7db0"
    end
  end

  def install
    bin.install "spinup"
  end

  test do
    system "#{bin}/spinup", "version"
  end
end
