# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spinup < Formula
  desc "Simple command line interface for spinup"
  homepage "https://github.com/YaleSpinup/spinup-cli"
  version "0.4.0-pre02"
  license "AGPL-3.0-or-later"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/spinup-cli/releases/download/v0.4.0-pre02/spinup-cli_0.4.0-pre02_darwin_amd64.tar.gz"
      sha256 "155734d06eca43fd487cb9f28dd9bc1dbfed19676d9e180f95fd568691c8335b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/YaleSpinup/spinup-cli/releases/download/v0.4.0-pre02/spinup-cli_0.4.0-pre02_darwin_arm64.tar.gz"
      sha256 "b5b1033249b7a8ecfa184afd0fb972c4baf77fc45bd02529652f6fa9d2686fc2"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/spinup-cli/releases/download/v0.4.0-pre02/spinup-cli_0.4.0-pre02_linux_amd64.tar.gz"
      sha256 "9936a1b77e7efdfdacefc983251645778da666cb531813f9feb6cc02fccd5d19"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YaleSpinup/spinup-cli/releases/download/v0.4.0-pre02/spinup-cli_0.4.0-pre02_linux_arm64.tar.gz"
      sha256 "2c7e5eacbc5200416b1e0b2c00a7a4421e675e764cc0575768c340273350867d"
    end
  end

  def install
    bin.install "spinup"
  end

  test do
    system "#{bin}/spinup", "version"
  end
end
