# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Splat < Formula
  desc "Bootstrap new Spinup APIs"
  homepage "https://github.com/YaleSpinup/splat"
  version "0.4.3"
  license "AGPL-3.0-or-later"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/splat/releases/download/v0.4.3/splat_0.4.3_darwin_amd64.tar.gz"
      sha256 "c49a1e49837d2676e639b162494c0d26bac3860c17715b11b71d7908e27c4b0b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/YaleSpinup/splat/releases/download/v0.4.3/splat_0.4.3_darwin_arm64.tar.gz"
      sha256 "d47b86ddde0fa3e11869007289ae03c4fb58a1e258546c73fb0d34a55f063289"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/splat/releases/download/v0.4.3/splat_0.4.3_linux_amd64.tar.gz"
      sha256 "9fafb87106ea867cb4732e1a543f24e5c521da326328fd70de1a118e95079e67"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YaleSpinup/splat/releases/download/v0.4.3/splat_0.4.3_linux_arm64.tar.gz"
      sha256 "9bb985a139dcead5e3d1cab797babdd92ebcd451f0a31bfcc7e06598c9cf881a"
    end
  end

  def install
    bin.install "splat"
  end

  test do
    system "#{bin}/splat", "version"
  end
end
