# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Splat < Formula
  desc "Bootstrap new Spinup APIs"
  homepage "https://github.com/YaleSpinup/splat"
  version "0.4.3-pre18"
  license "AGPLv3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/splat/releases/download/v0.4.3-pre18/splat_0.4.3-pre18_darwin_amd64.tar.gz"
      sha256 "7f307a8431fcd2be0b86cb2a21276aa834768fb3ed7e42271ef387a4819736e0"
    end
    if Hardware::CPU.arm?
      url "https://github.com/YaleSpinup/splat/releases/download/v0.4.3-pre18/splat_0.4.3-pre18_darwin_arm64.tar.gz"
      sha256 "9a00058549431a580bccb70384bc333e119123b3c77f4997704685de5a21a1b6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/splat/releases/download/v0.4.3-pre18/splat_0.4.3-pre18_linux_amd64.tar.gz"
      sha256 "d2f881f5578ed1ee187020a559be6e6fc179f94260e1207692cf43ead3721ac8"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YaleSpinup/splat/releases/download/v0.4.3-pre18/splat_0.4.3-pre18_linux_arm64.tar.gz"
      sha256 "dd92885e8653bbdb1bbde7888dbb5a64ace28281a1978d68b61a8f02821b823b"
    end
  end

  def install
    bin.install "splat"
  end

  test do
    system "#{bin}/splat version"
  end
end
