# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toker < Formula
  desc "A simple token management tool"
  homepage "https://github.com/YaleSpinup/toker"
  version "0.2.0-pre01"
  license "AGPL-3.0-or-later"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.2.0-pre01/toker_0.2.0-pre01_darwin_amd64.tar.gz"
      sha256 "70378fef900b0702617d28f544f00fea3b7b8a356fdca970108f0e3c6176a7b3"
    end
    if Hardware::CPU.arm?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.2.0-pre01/toker_0.2.0-pre01_darwin_arm64.tar.gz"
      sha256 "d7df6270654db859ffd866ec4a090560b157d0fbd65eb3f31f83802c8be68bff"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.2.0-pre01/toker_0.2.0-pre01_linux_amd64.tar.gz"
      sha256 "ad25dac75ec82cd723ebabb6f6e011b3bee80b8de2d2026b4f669173688af53e"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.2.0-pre01/toker_0.2.0-pre01_linux_arm64.tar.gz"
      sha256 "6c6020c89e2bf3423d3bfd91ea0d33db08f5b38013e0b73099a30e362416818e"
    end
  end

  def install
    bin.install "toker"
  end

  test do
    system "#{bin}/toker", "version"
  end
end
