# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toker < Formula
  desc "Simple token management tool"
  homepage "https://github.com/YaleSpinup/toker"
  version "0.2.0"
  license "AGPL-3.0-or-later"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.2.0/toker_0.2.0_darwin_amd64.tar.gz"
      sha256 "4455cba3ae8346e6a8203654a28331a93a73387c9dcc5ecacaaf908356a28476"
    end
    if Hardware::CPU.arm?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.2.0/toker_0.2.0_darwin_arm64.tar.gz"
      sha256 "82a846937a1748b8a7ff2b64a55e5241aca08c12a79376da4563a382c911c5db"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.2.0/toker_0.2.0_linux_amd64.tar.gz"
      sha256 "c5b50b8e6a75acd75e0dcb80baf62a2845dc3dc58b6c999b6ac95a45d50cd2b6"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.2.0/toker_0.2.0_linux_arm64.tar.gz"
      sha256 "62f3fab3afe433e000d5c67f3c7e3500974ab003563c7eb9a64e4ef9da2ebc2d"
    end
  end

  def install
    bin.install "toker"
  end

  test do
    system "#{bin}/toker", "version"
  end
end
