# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toker < Formula
  desc "Simple token management tool"
  homepage "https://github.com/YaleSpinup/toker"
  version "0.2.1"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.2.1/toker_0.2.1_darwin_amd64.tar.gz"
      sha256 "36b695c2e0dafbbe5057a53de3f978c4b64a85e17f3acc7e4a20f76357eee488"

      def install
        bin.install "toker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.2.1/toker_0.2.1_darwin_arm64.tar.gz"
      sha256 "93ab20843d8758fe221b55efcc0a876e0b62ee925a949c6a20e23cfa9857ad9e"

      def install
        bin.install "toker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.2.1/toker_0.2.1_linux_amd64.tar.gz"
      sha256 "df26f38c49e09bbc852355db619c7e040df28c078b4d84b592329f6ac2ef0baf"

      def install
        bin.install "toker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.2.1/toker_0.2.1_linux_arm64.tar.gz"
      sha256 "4506037dcee2a816058d79c909c17bff989eaef7e2656210a6c6d08e60398fa0"

      def install
        bin.install "toker"
      end
    end
  end

  test do
    system "#{bin}/toker", "version"
  end
end
